name: menu_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  control: ^0.2.0
  flutter:
    sdk: flutter
  l: ^5.0.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/menus/
